/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "brand-bg": "#fcfcfc",
        "brand-ink": "#1a1a1a",
        "brand-muted": "#757575",
        "brand-accent": "#8c8c8c",
        "light-bg": "#f5f5f0",
        "dark-text": "#1a1a1a",
        "on-secondary-fixed": "#1c1b1b",
        "surface-dim": "#dcd9d9",
        "on-surface": "#1c1b1b",
        "primary-fixed": "#dde5d8",
        "inverse-surface": "#313030",
        "background": "#fcf9f8",
        "surface-container-highest": "#e5e2e1",
        "secondary-container": "#e2dfde",
        "on-background": "#1c1b1b",
        "on-tertiary-fixed-variant": "#474646",
        "primary": "#596156",
        "surface-container-high": "#eae7e7",
        "on-surface-variant": "#444842",
        "tertiary-fixed": "#e5e2e1",
        "on-primary-fixed": "#161d15",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f0eded",
        "tertiary": "#5f5e5e",
        "inverse-primary": "#c1c9bc",
        "tertiary-fixed-dim": "#c9c6c5",
        "secondary-fixed-dim": "#c8c6c5",
        "surface": "#fcf9f8",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#c1c9bc",
        "surface-variant": "#e5e2e1",
        "primary-container": "#cad2c5",
        "secondary-fixed": "#e5e2e1",
        "on-primary-container": "#535b50",
        "outline": "#757872",
        "on-secondary-container": "#636262",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#595858",
        "on-tertiary-fixed": "#1c1b1b",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary-fixed-variant": "#474746",
        "outline-variant": "#c5c7c0",
        "on-primary-fixed-variant": "#41493f",
        "secondary": "#5f5e5e",
        "on-error": "#ffffff",
        "surface-bright": "#fcf9f8",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#d2cfce",
        "on-error-container": "#93000a",
        "surface-container-low": "#f6f3f2",
        "surface-tint": "#596156"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "sans": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "serif": ["Cormorant Garamond", "serif"],
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
